-- select * from MSysComplexType_Decimal
-- select * from Tables;
-- select * from MSysComplexType_Text
-- select * from MSysComplexType_GUID
-- select * from MSysComplexType_IEEEDouble
-- select * from MSysComplexType_IEEESingle
-- select * from MSysComplexType_Long
-- select * from MSysComplexType_Short
-- select * from MSysComplexType_UnsignedByte
   select * from MSysRelationships
-- select * from MSysQueries
-- select * from MSysACEs
-- select * from MSysObjects
-- select * from MSysDb                              -- No table
-- select * from MSysComplexType_Attachment          -- No table
-- select * from Relationships
-- select * from Databases                           -- No table
-- select * from MSysComplexColumns
-- select * from MSysAccessStorage
-- select * from UserDefined                         -- No table
-- select * from SummaryInfo                         -- No table
-- select * from Forms
-- select * from Scripts
-- select * from Modules                             -- No table
-- select * from Reports
-- select * from SysRel
-- select * from DataAccessPages
-- select * from MSysNavPaneGroupCategories
-- select * from MSysNavPaneGroups
-- select * from MSysNavPaneGroupToObjects
-- select * from MSysNavPaneGroupCategoriesMSysNavPaneGroups
-- select * from MSysNavPaneGroupsMSysNavPaneGroupToObjects
